config/routes.rb
WorldWideWeb::Application.routes.draw do

  root :to => 'home#index'

  resources :home, only: [:index]

  resources :addresses

end

app/models/address.rb
class Address < ActiveRecord::Base
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_address, only: [:show, :edit, :update, :destroy]

  # GET /addresses
  # GET /addresses.json
  def index
    @addresses = Address.all.map { |a| [a.latitude, a.longitude, a.magnitude] }.flatten
    render json: [["Connectivity",[@addresses]],["Population",[@addresses]]]
  end

  # GET /addresses/1
  # GET /addresses/1.json
  def show
  end

  # GET /addresses/new
  # GET /addresses/new.json
  def new
    @address = Address.new
  end

  # GET /addresses/1/edit
  def edit
  end

  # POST /addresses
  # POST /addresses.json
  def create
    @address = Address.new(params[:address])

    respond_to do |format|
      if @address.save
        format.html { redirect_to @address, notice: 'Address was successfully created.' }
        format.json { render json: @address, status: :created, location: @address }
      else
        format.html { render action: "new" }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /addresses/1
  # PUT /addresses/1.json
  def update
    @address = Address.find(params[:id])

    respond_to do |format|
      if @address.update_attributes(params[:address])
        format.html { redirect_to @address, notice: 'Address was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @address = Address.find(params[:id])
    @address.destroy

    respond_to do |format|
      format.html { redirect_to addresses_url }
      format.json { head :no_content }
    end
  end

  private
  def set_address
    @address = Addres.find(params[:id])
  end

  def address_params
    params.require(:address).permit(:ip, :latitude, :longitude, :magnitude)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    expires_in 10.minutes, public: true
  end

end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/addresses/_form.html.erb
<%= form_for(@address) do |f| %>
  <% if @address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@address.errors.count, "error") %> prohibited this address from being saved:</h2>

      <ul>
      <% @address.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :magnitude %><br />
    <%= f.text_field :magnitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/addresses/edit.html.erb
<h1>Editing address</h1>

<%= render 'form' %>

<%= link_to 'Show', @address %> |
<%= link_to 'Back', addresses_path %>

app/views/addresses/index.html.erb
<h1>Listing addresses</h1>

<table>
  <tr>
    <th>Ip</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th>Magnitude</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @addresses.each do |address| %>
  <tr>
    <td><%= address.latitude %></td>
    <td><%= address.longitude %></td>
    <td><%= address.magnitude %></td>
    <td><%= link_to 'Show', address %></td>
    <td><%= link_to 'Edit', edit_address_path(address) %></td>
    <td><%= link_to 'Destroy', address, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Address', new_address_path %>

app/views/addresses/new.html.erb
<h1>New address</h1>

<%= render 'form' %>

<%= link_to 'Back', addresses_path %>

app/views/addresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Latitude:</b>
  <%= @address.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @address.longitude %>
</p>

<p>
  <b>Magnitude:</b>
  <%= @address.magnitude %>
</p>


<%= link_to 'Edit', edit_address_path(@address) %> |
<%= link_to 'Back', addresses_path %>

app/views/application/_footer.html.erb
<div class="navbar-static-bottom" style="margin: 25px; margin-bottom:15px">
  <p class="text-muted credit">Created by <a href="mailto:nicklombardi@gmail.com?Subject=SolarEyes">Nick Lombardi</a></p>
</div>

app/views/application/_navbar.html.erb
<nav class="navbar navbar-fixed-top" role="navigation">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
      <a class="navbar-brand" href="#">World Wide Web</a>
  </div>
  <div class="navbar-collapse collapse">
     <ul class="nav navbar-nav navbar-right">
      <p class="text-muted credit" style="margin-top:16px;">Created by <a href="mailto:nicklombardi@gmail.com?Subject=World Wide Web">Nick Lombardi</a>
      </p>
    </ul>
  </div>
</nav>

app/views/home/index.html.erb
  <body>

  <div id="container"></div>

  <div id="currentInfo">
    <span id="contentConnectivity" class="none"></span>
  </div>

  <script type="text/javascript">

    if(!Detector.webgl){
      Detector.addGetWebGLMessage();
    } else {

      var dataSet = ['Connectivity'];
      var container = document.getElementById('container');
      var globe = new DAT.Globe(container);
      console.log(globe);
      var i, tweens = [];

      var settime = function(globe, t) {
        return function() {
          new TWEEN.Tween(globe).to({time: t/dataSet.length},500).easing(TWEEN.Easing.Cubic.EaseOut).start();
          var y = document.getElementById('content'+dataSet[t]);
          if (y.getAttribute('class') === 'content active') {
            return;
          }
          var yy = document.getElementsByClassName('content');
          for(i=0; i<yy.length; i++) {
            yy[i].setAttribute('class','content');
          }
          y.setAttribute('class', 'content active');
        };
      };

      for(var i = 0; i<dataSet.length; i++) {
        var y = document.getElementById('content'+dataSet[i]);
        y.addEventListener('mouseover', settime(globe,i), false);
      }

      var xhr;
      TWEEN.start();

    //   $.ajax({
    //     url: '/addresses',
    //     type: 'get',
    //     dataType: 'json'
    //   }).done(function(data){
    //     for (i=0;i<data.length;i++) {
    //       globe.addData(data[i][1], {format: 'magnitude', name: data[i][0], animated: true});
    //     }
    //     globe.createPoints();
    //     settime(globe,0)();
    //     globe.animate();
    //     console.log(data);
    //   })
    // }

      xhr = new XMLHttpRequest();
      xhr.open('GET', '/assets/dataset.json', true);
      xhr.onreadystatechange = function(e) {
        if (xhr.readyState === 4) {
          if (xhr.status === 200) {
            var data = JSON.parse(xhr.responseText);
            window.data = data;
            for (i=0;i<data.length;i++) {
              globe.addData(data[i][1], {format: 'magnitude', name: data[i][0], animated: true});
            }
            globe.createPoints();
            settime(globe,0)();
            globe.animate();
          }
        }
      };
      xhr.send(null);
    }

  </script>



  </body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WorldWideWeb</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= javascript_include_tag "application" %>

<%= render 'navbar' %>

<%= yield %>

</body>
</html>